development:
  adapter: sqlite3
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: db/development.sqlite3
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 3306
  timeout: 5000
